version: '3'
volumes:
    dados:
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
        - 3333:3306
    volumes:
      - dados:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: igor

  backend:
    image: dotnet-image
    build:
      context: .
    ports:
      - 80:80